### PR TITLE
Increasing BLE power for more range and adding Python scripts for RPi

### PR DESCRIPTION
**Pull request by RapierXbox**
Increasing BLE power to the maximum of the ESP32 (9dBm) to [increase the range to about 10-100m.](https://fte.com/WebHelpII/BPA600/Content/Documentation/Conductive%20Testing/ClassicBTTransmitterClasses.htm)

### CODE REVIEW

**Comment by ckcr4lyf** [comment]
Thanks for the PR. I will try and test it offline and get back here eventually.

**Comment by RapierXbox** [comment]
also addet py script...i havent tested them jet but they should work...they are a moddet version of my crash

**Comment by ckcr4lyf** [comment]
I do not want to introduce any bluez / python related functionality to this project, it is intended purely for an ESP32.

**Comment by ckcr4lyf** [comment]
You're welcome to fork / make your own "Evil" related project based on python+linux if you'd like, the LICENSE for this project is very permissive.

**Comment by RapierXbox** [comment]
> I do not want to introduce any bluez / python related functionality to this project, it is intended purely for an ESP32.

np

**Comment by RapierXbox** [comment]
gonna reopen a pull without the python stuff

**Pull request closed without merging**
